name: deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: klakegg/hugo:0.101.0-ubuntu
    steps:
      - name: clone this repository
        uses: actions/checkout@v2
      - name: change directory
        run: cd src
      - name: print location
        run: pwd; ls;
      - name: build hugo site
        run: hugo
