name: deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: klakegg/hugo:0.101.0-ubuntu
    steps:
      - name: clone this repository
        uses: actions/checkout@v2
      - name: build hugo site
        run: hugo --minify
        working-directory: src
      - name: deploy build data to github.io repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_SECRET_KEY }}
          external_repository: mtsalt/mtsalt.github.io
          publish_dir: ./src/public
          publish_branch: main          
